### ISSUE TITLE
A compiling issue under Mac OS 苹果操作系统下编译的问题

### ISSUE THREAD

**Issue by han190** [Steve-Cheung-emct/upLaTeX-SZ.CLS#3]
# Descriptions of issues 问题描述
Hi, for those of you who don't speak Chinese I will follow the convention of the author and translate everything I wrote into English. Bare with me if the translation is confusing.:)

我按照您的提示在Mac下安装了字体。由于mac下的texlive 的路径跟windows下的不太一样，我把字体安装在了以下的路径，（并没有这个路径所以我创建了这个路径）
```
/usr/local/texlive/texmf-local/fonts/source/genko
```
I followed the instruction and tried to install those fonts. Since the directory of the texlive under Mac OS is different with that under Windows I copied everything into, ( there is no such a directory so I mkdir it)
```
/usr/local/texlive/texmf-local/fonts/source/genko
```

但是在编译完之后字体并没有被识别，应该是这个导致了字体不一致，而且有部分字缺漏。
But apparently the fonts were not installed correctly and some Chinese characters/Kanji are not shown.

左边为我用mac编辑的，右图为您原来的pdf。
where the left pdf file is what I compiled and the file on the right is the original main.pdf in the repository.
![image](https://user-images.githubusercontent.com/13799118/71066420-00d6c780-211f-11ea-850f-2c7e99ba52b6.png)

所以我的问题其实是，**Mac下字体到底安装在哪儿？**
So my question is, **those font files, where exactly should I put them?**

另外，repo中的`furiknkt.sty`文件我在mac下打开的时候是乱码，这导致我第一次编译失败。我在mac下的terminal默认设置是utf-8，所以也不知道是为什么……我重新从网上copy了一份下来，就成功了。
Besides, the text in the `furiknkt.sty` is garbled and thereby my first attempt compiling failed. I copied the file from your repo directly and it went through. IDK why...

**Comment by Steve-Cheung-emct** [comment]
（可由word繁轉簡）

首先，furiknkt.sty 是藤田 眞作老師編寫的振假名宏包。元来是 SJIS 編碼，直接打開確實會亂碼。可在 stonesetings.sty 中直接屏蔽它。檢查頭注（tochu.sty）包中，有此宏可一并屏蔽。

第二，觀察圖片，你的字體默認是 HiraginoSerifProN-W3.otf 所以沒有 Pr5 Pr6 的漢字。這個我也沒有辦法解決，你要自己想辦法換字体才行。

第三，Adobe Japan 1-6 是一個缺字不多的子集。關於此編碼集，更多信息請查閲技術文檔 5078.Adobe-Japan1-6.pdf 

第四，我使用的字符映射表如下：

```latex
% TEXT, JIS04

uphminln-h	UniJIS2004-UTF16-H	FOT-TsukuAOldMinPr6N-L.otf
uphminln-v	UniJIS2004-UTF16-V	FOT-TsukuAOldMinPr6N-L.otf
uphminrn-h	UniJIS2004-UTF16-H	FOT-TsukuAOldMinPr6N-M.otf
uphminrn-v	UniJIS2004-UTF16-V	FOT-TsukuAOldMinPr6N-M.otf
uphminbn-h	UniJIS2004-UTF16-H	FOT-TsukuAOldMinPr6N-B.otf
uphminbn-v	UniJIS2004-UTF16-V	FOT-TsukuAOldMinPr6N-B.otf
uphgothrn-h	UniJIS2004-UTF16-H	A-OTF-SeiKaiCB1Pr5-Regular.otf
uphgothrn-v	UniJIS2004-UTF16-V	A-OTF-SeiKaiCB1Pr5-Regular.otf
uphgothbn-h	UniJIS2004-UTF16-H	A-OTF-ShinseiKaiPr5-CBSK1.otf
uphgothbn-v	UniJIS2004-UTF16-V	A-OTF-ShinseiKaiPr5-CBSK1.otf
uphgothebn-h	UniJIS2004-UTF16-H	DFGanShinKeiPro5-W7.otf
uphgothebn-v	UniJIS2004-UTF16-V	DFGanShinKeiPro5-W7.otf
uphmgothrn-h	UniJIS2004-UTF16-H	FOT-UDMarugoSmallPr6N-M.otf
uphmgothrn-v	UniJIS2004-UTF16-V	FOT-UDMarugoSmallPr6N-M.otf
```

由 kozuka-pr6n map 改編而來。方法見于入門貼。

第五、関于字体

如果TEX系統報告找不到 TFM。執行 `mktexlsr`命令刷新 。

如果map中字體名稱寫錯，將反饋：找不到 `xxx.ttf/otf` 意思系統找不到對應的真實字體文件（這個字體在Windows中必須存儲在 `C:\Windows\Fonts` 之中，或由 `C:\texlive\2019\texmf.cnf` 第十行目，爲之配置TeX 字體存儲目錄。（OSX系統同理，可類推實踐）

希望可以解決您的問題。

**Comment by Steve-Cheung-emct** [comment]
OS X 系統的字体，安装目录十分诡异。我沒有尝试在 OS X 上配置字体的经验。所以沒有办法知道 OS X 的字体策略。

TEX 系统中，根据 texmf.cnf 配置的向量，可以指向一个或多个目录。可以将字体集中放置到某个目录中。就不必安装到 OS X 系统。（缺点嘛，你可能无法将这些字体用于桌面显示，因为他们都沒有安装到系统中，但是可以利用 dvi 或者 dvipdfmx 将 *.dvi 输出為 PDF 。

至于这些字体如何获取，则八仙过海，各显神通啦……

**Comment by Steve-Cheung-emct** [comment]
附 5078.Adobe-Japan1-6.pdf

[5078.Adobe-Japan1-6.pdf](https://github.com/Steve-Cheung-emct/upLaTeX-SZ.CLS/files/3977401/5078.Adobe-Japan1-6.pdf)

关于字体，wo我正在着手做一个总结。

![fig01](https://user-images.githubusercontent.com/26833892/71070071-f36c1c80-21b4-11ea-85e7-091c095ce613.png)

**Comment by rossea** [comment]
我使用这个模版在MacOS 10.13.6 上，用kanji-config-updmap-sys配置日文字体也存在问题。我的解决方法如下：

我的系统配置：
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G11023

我的PatchSet: 2020-001
我的MacTex是2019版，完整安装。

问题重现：
配置 OSFONTDIR 环境变量，用字体册安装所需字体后，仍存在问题。
$ sudo mktexlsr
$ sudo kanji-config-updmap-sys --jis2004 sourcehan
**Cannot find ptex-fontmaps-macos-data.dat, skipping!**
Setting up ... sourcehan (AI0) for ja
……
这时，sourcehan的字体映射还是无法使用，会提示找不到相应虚拟字体。

解决方法：
MacOS的字体管理方式与windows和Linux不同。不使用fc-list。
XeLaTeX 等，通过字体文件名调用字体需要 kpathsea 库的协助。默认情况下，kpathsea 会搜索 MacTeX 自己的目录树（TEXMF）。如果希望 kpathsea 搜索系统字体目录（即通过“字体册”安装的字体），在MacTeX 2019中，还需要检查以下两点：
一、配置 OSFONTDIR 环境变量：
$ sudo vi /usr/local/texlive/2019/texmf.cnf
加上：OSFONTDIR = /Library/Fonts//:~/Library/Fonts//
二、安装macos下的fontmaps，并重建fontmaps缓存

$ sudo tlmgr update --self --all

$ sudo tlmgr repository add http://contrib.texlive.info/current tlcontrib
$ sudo tlmgr pinning add tlcontrib '*'
$ sudo tlmgr install ptex-fontmaps-macos cjk-gs-integrate-macos

$ sudo cjk-gs-integrate --link-texmf --cleanup
$ sudo cjk-gs-integrate-macos --link-texmf
$ sudo mktexlsr

最后，重新执行：
$ sudo kanji-config-updmap-sys --jis2004 sourcehan

仅验证对我的配置可用。
其他参见：https://qiita.com/kauplan/items/44ac2ecc37a31babb577
